export const NAV_ITEMS = [
  ["Dashboard", "/dashboard"],
  ["Cases", "/dashboard/cases"],
  ["Clients", "/dashboard/clients"],
  ["Calendar", "/dashboard/calendar"],
  ["Tasks", "/dashboard/tasks"],
  ["Documents", "/dashboard/documents"],
  ["Precedents", "/dashboard/precedents"],
  ["Messages", "/dashboard/messages"],
  ["Billing", "/dashboard/billing"],
  ["Invoices", "/dashboard/invoices"],
  ["Time Entries", "/dashboard/time-entries"],
  ["Finance", "/dashboard/finance"],
  ["Trust", "/dashboard/trust"],
  ["Expenses", "/dashboard/expenses"],
  ["Team", "/dashboard/team"],
  ["Reports", "/dashboard/reports"],
  ["Audit Logs", "/dashboard/audit-logs"],
  ["Settings", "/dashboard/settings"],
];
